export const ProjectsData = [
    {
        title: "Luminex Lux - An Online Jewelry Shop",
        desc: "Luminex is an online jewelry shop. Seamlessly navigate through stunning product details, secure user authentication, and a smooth shopping cart. Powered by Next.js, TypeScript, Redux, Redux Persist, SwiperJS, SWR, CLSX, Lenix, and more.",
        tags: ["Next.js", "TypeScript", "Redux","Redux Persist","SwiperJS","SWR","CLSX","Lenix","Axios","Mongodb","Framer","Motion","Aos","Tailwind CSS"],
        liveLink: "https://luminex-lux.vercel.app",
        frontEndLink: "https://github.com/kajal-rekha/luminex-client.git",
        backendLink: "https://github.com/kajal-rekha/luminex-server.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1704908056/Screenshot_69_gczjrg.png",
    },
    {
        title: "AeroTix - An Online Air Ticket Booking Application",
        desc: "Aero-Tix is an online air ticket booking application built with a modern tech stack to provide users with a seamless and efficient booking experience. The application allows users to search for flights, book tickets, and manage their reservations with ease.",
        tags: [ "Next.js",
            "TypeScript",
            "Redux-Persist",
            "Node.js",
            "Exxpress.js",
            "Stripe",
            "JWT",
            "Axios",
            "SWR",
            "Mongodb",
            "Tailwind CSS",
            "clsx",
            "Swiper.js",
            "Lenis",],
        liveLink: "https://aero-tix.vercel.app/",
        frontEndLink: "https://github.com/kajal-rekha/aero-tix-client.git",
        backendLink: "https://github.com/kajal-rekha/aero-tix-server.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1756664617/aero-her_qegoo8.png"
    },
    {
        title: "Cordemy - An Online Learning Platform",
        desc:  "Cordemy is an innovative online learning platform that provides a unique and immersive educational experience. It leverages a powerful tech stack, including Next.js, React, Prisma, Stripe, NextAuth, Tailwind CSS, clsx, and Axios, to deliver a feature-rich platform for learners and instructors.",
        tags: ["Next.js",
            "Prisma",
            "Stripe",
            "NextAuth",
            "Axios",
            "Mongodb",
            "Tailwind CSS",
            "Context-api",],
        liveLink: "https://cordemy-theta.vercel.app",
        frontEndLink: "https://github.com/kajal-rekha/cordemy.git",
        backendLink: "https://github.com/kajal-rekha/cordemy.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1687459898/Screenshot_53_lcf8zk.png"
    },
    {
        title: "Celestia _ An AI powered chat assistance",
        desc:  "Celestia is a smart, interactive chat solution designed to deliver accurate and contextually relevant responses to user queries. Built with Node.js, Express.js, MongoDB, and string-similarity algorithms for the backend, it ensures seamless data handling and precise answer matching. ",
        tags: ["React.js",
            "Node.js",
            "Express.js",
            "MongoDB",
            "string-similiarity",
            "Tailwind CSS",],
        liveLink: "https://celestia-fawn.vercel.app",
        frontEndLink: "https://github.com/kajal-rekha/celestia-client.git",
        backendLink: "https://github.com/kajal-rekha/celestia-server.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1756667662/celestia_hzvjtg.png"
    },
    {
        title: "Tech Alpha _ An Ecommerce Website",
        desc: "This is an e-commerce project built using React, Redux, and Tailwind CSS. It is a modern, fast and responsive web application designed for an optimal shopping experience. The project makes use of Redux for state management and Tailwind CSS for styling to deliver an efficient and visually appealing user interface.",
        tags: [ "React",
            "Redux",
            "Redux Thunk",
            "Redux Toolkit",
            "Axios",
            "Tailwind CSS",],
       liveLink: "https://tech-alpha-ecommerce.netlify.app/",
        frontEndLink: "https://github.com/kajal-rekha/tech-alpha.git",
        backendLink: "https://github.com/kajal-rekha/tech-alpha-server.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1677934825/Screenshot_36_efvmrv.png"
    },
    {
        title: "Proxima - A Powerful Project Management App",
        desc:  "Proxima is a secure and powerful project management system built with React, Express, Tailwind CSS, Node.js, and MongoDB. It features JWT authentication, easy project creation, task assignment, and progress tracking. Proxima is highly customizable, responsive, and scalable.",
        tags: ["React",
            "Nodejs",
            "Express",
            "Jwt",
            "Mongodb",
            "Tailwind CSS",
            "Context-api",],
         liveLink: "https://proxima-app-project.netlify.app",
        frontEndLink: "https://github.com/kajal-rekha/proxima-client.git",
        backendLink: "https://github.com/kajal-rekha/proxima-server.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1677934511/Screenshot_33_b3fq76.png",
    },
    {
        title: "Foodvarse - A Recipe Finder Web Application",
        desc: "Foodverse is a recipe web application, where an user can search different kinds of recipe and find the necessary ingredients for the specific recipe item. Also a recipe item can be saved into the local storage of the browser. ",
        tags: ["React.js", " React Router", "Tailwind CSS"],
        liveLink: "https://foodvarse.netlify.app/",
        frontEndLink: "https://github.com/kajal-rekha/foodvarse.git",
        image:"https://res.cloudinary.com/dh0ado2ir/image/upload/v1675278752/Screenshot_4_rfupr3.png",
    },
    {
        title: "Immemorial: 90's Memory",
        desc:  "This repository contains a React application that allows users to reminisce about their memories from the 90s. The application utilizes React Router for navigation between pages, and GSAP (GreenSock Animation Platform) for animations to enhance the user experience. Users can create, edit, and view their own 90s memories in a fun and interactive way. ",
        tags: ["React.js",
            "React Router",
            "GSAP "],
       liveLink: "https://immemorial-project.netlify.app/",
        frontEndLink: "https://github.com/kajal-rekha/immemorial.git",
        image: "https://res.cloudinary.com/dh0ado2ir/image/upload/v1692878024/Screenshot_9_fpzwdb.png",
    },
   
    
]
